DROP TABLE IQUANTIFY.ANSWERS;
DROP TABLE IQUANTIFY.ENCRYPTED_PAYLOAD;
DROP TABLE IQUANTIFY.IQUANTIFY;
DROP TABLE IQUANTIFY.PERFORMANCES;
DROP TABLE IQUANTIFY.RESOURCES_QA;
DROP TABLE IQUANTIFY.RESOURCES;
DROP TABLE IQUANTIFY.REVENUE;
DROP TABLE IQUANTIFY.SESSIONS;
DROP TABLE IQUANTIFY.PERSON;
DROP TABLE IQUANTIFY.BD_QA;
DROP TABLE IQUANTIFY.QUESTIONNAIRE;
DROP TABLE IQUANTIFY.BROKER_DEALER;

DROP SEQUENCE IQUANTIFY.ANSWERS_SEQ;
DROP SEQUENCE IQUANTIFY.ENCRYPTED_PAYLOAD_SEQ;
DROP SEQUENCE IQUANTIFY.IQUANTIFY_SEQ;
DROP SEQUENCE IQUANTIFY.RESOURCES_QA_SEQ;
DROP SEQUENCE IQUANTIFY.REVENUE_SEQ;



CREATE SEQUENCE IQUANTIFY.ENCRYPTED_PAYLOAD_SEQ START WITH 1 CACHE 20;

CREATE SEQUENCE IQUANTIFY.IQUANTIFY_SEQ START WITH 1 CACHE 20;

CREATE SEQUENCE IQUANTIFY.RESOURCES_QA_SEQ START WITH 1 CACHE 20;

CREATE SEQUENCE IQUANTIFY.REVENUE_SEQ START WITH 1 CACHE 20;

CREATE TABLE IQUANTIFY.BROKER_DEALER ( 
	ID                   number(38,0)  NOT NULL,
	EXTERNAL_ID          number(38,0)  ,
	BD_NAME              varchar2(100)  ,
	DOMAIN_NAME          varchar2(200)  ,
	VERSION              varchar2(20)  NOT NULL,
	CREATED_BY           varchar2(100)  NOT NULL,
	CREATED_ON           timestamp(6)  NOT NULL,
	UPDATED_BY           varchar2(100)  ,
	UPDATED_ON           timestamp(6)  ,
	CONSTRAINT BROKER_DEALER_PK PRIMARY KEY ( ID ) ,
	CONSTRAINT BROKER_DEALER_UK1 UNIQUE ( EXTERNAL_ID ) ,
	CONSTRAINT BROKER_DEALER_UK2 UNIQUE ( BD_NAME ) ,
	CONSTRAINT BROKER_DEALER_UK3 UNIQUE ( DOMAIN_NAME ) 
 )
TABLESPACE IQUANTIFY_DATA;

CREATE TABLE IQUANTIFY.ENCRYPTED_PAYLOAD ( 
	ID                   number(38,0)  NOT NULL,
	PAYLOAD              clob  NOT NULL,
	CREATED_BY           varchar2(100)  NOT NULL,
	CREATED_ON           timestamp(6)  NOT NULL,
	UPDATED_BY           varchar2(100)  ,
	UPDATED_ON           timestamp(6)  ,
	CONSTRAINT ENCRYPTED_PAYLOAD_PK PRIMARY KEY ( ID ) 
 )
TABLESPACE IQUANTIFY_DATA;

CREATE TABLE IQUANTIFY.PERFORMANCES ( 
	ID                   number(38,0)  NOT NULL,
	USER_COUNT           number(38,0)  NOT NULL,
	PERFORMANCE          number  NOT NULL,
	CREATED_BY           varchar2(100)  NOT NULL,
	CREATED_ON           timestamp(6)  NOT NULL,
	UPDATED_BY           varchar2(100)  ,
	UPDATED_ON           timestamp(6)  ,
	CONSTRAINT PERFORMANCE_PK PRIMARY KEY ( ID ) 
 )
TABLESPACE IQUANTIFY_DATA;

CREATE TABLE IQUANTIFY.PERSON ( 
	ID                   varchar2(100)  NOT NULL,
	FIRST_NAME           varchar2(50)  NOT NULL,
	LAST_NAME            varchar2(50)  NOT NULL,
	EMAIL                varchar2(100)  NOT NULL,
	CONSULTANT_EMAIL     varchar2(100)  ,
	BD_ID                number(38,0)  NOT NULL,
	IS_INTERNAL          varchar2(1)  NOT NULL,
	CREATED_BY           varchar2(100)  NOT NULL,
	CREATED_ON           timestamp(6)  NOT NULL,
	UPDATED_BY           varchar2(100)  ,
	UPDATED_ON           timestamp(6)  ,
	CONSTRAINT PERSON_PK PRIMARY KEY ( ID ) ,
	CONSTRAINT PERSON_FK1 FOREIGN KEY ( BD_ID ) REFERENCES IQUANTIFY.BROKER_DEALER( ID )  
 )
TABLESPACE IQUANTIFY_DATA;

CREATE INDEX PERSON_IDX ON IQUANTIFY.PERSON ( BD_ID ) TABLESPACE IQUANTIFY_INDEX;

CREATE TABLE IQUANTIFY.QUESTIONNAIRE ( 
	ID                   number(38,0)  NOT NULL,
	NAME                 varchar2(50)  NOT NULL,
	QUESTIONS            clob  NOT NULL,
	VERSION              varchar2(20)  NOT NULL,
	STATUS               varchar2(20)  NOT NULL,
	CREATED_BY           varchar2(100)  NOT NULL,
	CREATED_ON           timestamp(6)  NOT NULL,
	UPDATED_BY           varchar2(100)  ,
	UPDATED_ON           timestamp(6)  ,
	CONSTRAINT QUESTIONNAIRE_PK PRIMARY KEY ( ID ) 
 )
TABLESPACE IQUANTIFY_DATA;

CREATE TABLE IQUANTIFY.RESOURCES ( 
	ID                   number(38,0)  NOT NULL,
	VERSION              varchar2(20)  NOT NULL,
	LINKS                clob  NOT NULL,
	DESCRIPTION          varchar2(20)  NOT NULL,
	CREATED_BY           varchar2(100)  NOT NULL,
	CREATED_ON           timestamp(6)  NOT NULL,
	UPDATED_BY           varchar2(100)  ,
	UPDATED_ON           timestamp(6)  ,
	CONSTRAINT RESOURCES_PK PRIMARY KEY ( ID ) 
 )
TABLESPACE IQUANTIFY_DATA;

CREATE TABLE IQUANTIFY.REVENUE ( 
	ID                   number(38,0)  NOT NULL,
	PERSON_ID            varchar2(100)  NOT NULL,
	YEARLY_REVENUE       number  NOT NULL,
	QUALIFIED_PERC       number  NOT NULL,
	NON_RECURRING_PERC   number  NOT NULL,
	CREATED_BY           varchar2(100)  NOT NULL,
	CREATED_ON           timestamp(6)  NOT NULL,
	UPDATED_BY           varchar2(100)  ,
	UPDATED_ON           timestamp(6)  ,
	CONSTRAINT REVENUE_PK PRIMARY KEY ( ID ) ,
	CONSTRAINT REVENUE_FK1 FOREIGN KEY ( PERSON_ID ) REFERENCES IQUANTIFY.PERSON( ID )  
 )
TABLESPACE IQUANTIFY_DATA;

CREATE INDEX REVENUE_IDX ON IQUANTIFY.REVENUE ( PERSON_ID ) TABLESPACE IQUANTIFY_INDEX;

CREATE TABLE IQUANTIFY.SESSIONS ( 
	ID                   varchar2(100)  NOT NULL,
	PERSON_ID            varchar2(100)  NOT NULL,
	EXPIRES_ON           timestamp(6)  NOT NULL,
	SURVEY_STATUS        varchar2(20)  NOT NULL,
	IS_INTERNAL          varchar2(1)  NOT NULL,
	CREATED_BY           varchar2(100)  NOT NULL,
	CREATED_ON           timestamp(6)  NOT NULL,
	UPDATED_BY           varchar2(100)  ,
	UPDATED_ON           timestamp(6)  ,
	CONSTRAINT SESSIONS_PK PRIMARY KEY ( ID ) ,
	CONSTRAINT SESSIONS_FK1 FOREIGN KEY ( PERSON_ID ) REFERENCES IQUANTIFY.PERSON( ID )  
 )
TABLESPACE IQUANTIFY_DATA;

CREATE INDEX SESSIONS_IDX ON IQUANTIFY.SESSIONS ( PERSON_ID ) TABLESPACE IQUANTIFY_INDEX;

CREATE TABLE IQUANTIFY.BD_QA ( 
	ID                   number(38,0)  NOT NULL,
	BD_ID                number(38,0)  NOT NULL,
	QUESTIONNAIRE_ID     number(38,0)  NOT NULL,
	VERSION              varchar2(20)  NOT NULL,
	STATUS               varchar2(20)  NOT NULL,
	CREATED_BY           varchar2(100)  NOT NULL,
	CREATED_ON           timestamp(6)  NOT NULL,
	UPDATED_BY           varchar2(100)  ,
	UPDATED_ON           timestamp(6)  ,
	CONSTRAINT BD_QA_PK PRIMARY KEY ( ID ) ,
	CONSTRAINT BD_QA_UK UNIQUE ( BD_ID, QUESTIONNAIRE_ID ) ,
	CONSTRAINT BD_QA_FK1 FOREIGN KEY ( BD_ID ) REFERENCES IQUANTIFY.BROKER_DEALER( ID )  ,
	CONSTRAINT BD_QA_FK2 FOREIGN KEY ( QUESTIONNAIRE_ID ) REFERENCES IQUANTIFY.QUESTIONNAIRE( ID )  
 )
TABLESPACE IQUANTIFY_DATA;

CREATE INDEX BD_QA_IDX1 ON IQUANTIFY.BD_QA ( BD_ID ) TABLESPACE IQUANTIFY_INDEX;

CREATE INDEX BD_QA_IDX2 ON IQUANTIFY.BD_QA ( QUESTIONNAIRE_ID ) TABLESPACE IQUANTIFY_INDEX;

CREATE TABLE IQUANTIFY.IQUANTIFY ( 
	ID                   number(38,0)  NOT NULL,
	QUESTIONNAIRE_ID     number(38,0)  NOT NULL,
	PERFORMANCE          number  NOT NULL,
	I_QUANTIFY           number  NOT NULL,
	PERSON_ID            varchar2(100)  NOT NULL,
	CREATED_BY           varchar2(100)  NOT NULL,
	CREATED_ON           timestamp(6)  NOT NULL,
	UPDATED_BY           varchar2(100)  ,
	UPDATED_ON           timestamp(6)  ,
	CONSTRAINT IQUANTIFY_PK PRIMARY KEY ( ID ) ,
	CONSTRAINT IQUANTIFY_FK2 FOREIGN KEY ( PERSON_ID ) REFERENCES IQUANTIFY.PERSON( ID )  ,
	CONSTRAINT IQUANTIFY_FK1 FOREIGN KEY ( QUESTIONNAIRE_ID ) REFERENCES IQUANTIFY.QUESTIONNAIRE( ID )  
 )
TABLESPACE IQUANTIFY_DATA;

CREATE INDEX IQUANTIFY_IDX1 ON IQUANTIFY.IQUANTIFY ( QUESTIONNAIRE_ID ) TABLESPACE IQUANTIFY_INDEX;

CREATE INDEX IQUANTIFY_IDX2 ON IQUANTIFY.IQUANTIFY ( PERSON_ID ) TABLESPACE IQUANTIFY_INDEX;

CREATE INDEX IQUANTIFY_IDX3 ON IQUANTIFY.IQUANTIFY ( PERSON_ID, CREATED_ON ) TABLESPACE IQUANTIFY_INDEX;

CREATE TABLE IQUANTIFY.RESOURCES_QA ( 
	ID                   number(38,0)  NOT NULL,
	BD_QA_ID             number(38,0)  NOT NULL,
	QUESTION_ID          number(38,0)  NOT NULL,
	RES_ID               number(38,0)  NOT NULL,
	RANKING              number(38,0)  NOT NULL,
	LOWER_LIMIT          number(38,0)  NOT NULL,
	UPPER_LIMIT          number(38,0)  NOT NULL,
	VERSION              varchar2(20)  NOT NULL,
	STATUS               varchar2(20)  NOT NULL,
	CREATED_BY           varchar2(100)  NOT NULL,
	CREATED_ON           timestamp(6)  NOT NULL,
	UPDATED_BY           varchar2(100)  ,
	UPDATED_ON           timestamp(6)  ,
	CONSTRAINT RESOURCES_QA_PK PRIMARY KEY ( ID ) ,
	CONSTRAINT RESOURCES_QA_FK1 FOREIGN KEY ( BD_QA_ID ) REFERENCES IQUANTIFY.BD_QA( ID )  ,
	CONSTRAINT RESOURCES_QA_FK3 FOREIGN KEY ( RES_ID ) REFERENCES IQUANTIFY.RESOURCES( ID )  
 )
TABLESPACE IQUANTIFY_DATA;

CREATE INDEX RESOURCES_QA_IDX1 ON IQUANTIFY.RESOURCES_QA ( BD_QA_ID ) TABLESPACE IQUANTIFY_INDEX;

CREATE INDEX RESOURCES_QA_IDX2 ON IQUANTIFY.RESOURCES_QA ( RES_ID ) TABLESPACE IQUANTIFY_INDEX;

CREATE TABLE IQUANTIFY.ANSWERS ( 
	ID                   number(38,0)  NOT NULL,
	I_QUANTIFY_ID        number(38,0)  NOT NULL,
	QUESTION_ID          number(38,0)  NOT NULL,
	QUESTION             varchar2(1000)  NOT NULL,
	ANSWER               varchar2(1000)  NOT NULL,
	WEIGHT               number(38,0)  NOT NULL,
	CREATED_BY           varchar2(100)  NOT NULL,
	CREATED_ON           timestamp(6)  NOT NULL,
	UPDATED_BY           varchar2(100)  ,
	UPDATED_ON           timestamp(6)  ,
	CONSTRAINT ANSWERS_PK PRIMARY KEY ( ID ) ,
	CONSTRAINT ANSWERS_UK UNIQUE ( I_QUANTIFY_ID, QUESTION_ID ) ,
	CONSTRAINT ANSWERS_FK1 FOREIGN KEY ( I_QUANTIFY_ID ) REFERENCES IQUANTIFY.IQUANTIFY( ID )  
 )
TABLESPACE IQUANTIFY_DATA;

CREATE INDEX ANSWERS_IDX1 ON IQUANTIFY.ANSWERS ( I_QUANTIFY_ID ) TABLESPACE IQUANTIFY_INDEX;

CREATE INDEX ANSWERS_IDX2 ON IQUANTIFY.ANSWERS ( QUESTION_ID ) TABLESPACE IQUANTIFY_INDEX;

CREATE OR REPLACE TRIGGER IQUANTIFY.ANSWERS_TRG
BEFORE INSERT ON ANSWERS
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ANSWERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE OR REPLACE TRIGGER IQUANTIFY.ENCRYPTED_PAYLOAD_TRG
BEFORE INSERT ON ENCRYPTED_PAYLOAD
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ENCRYPTED_PAYLOAD_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE OR REPLACE TRIGGER IQUANTIFY.IQUANTIFY_TRG
BEFORE INSERT ON IQUANTIFY
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT IQUANTIFY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE OR REPLACE TRIGGER IQUANTIFY.RESOURCES_QA_TRG
BEFORE INSERT ON RESOURCES_QA
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT RESOURCES_QA_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE OR REPLACE TRIGGER IQUANTIFY.REVENUE_TRG
BEFORE INSERT ON REVENUE
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT REVENUE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

